# syntax=docker/dockerfile:1
# check=error=true

ARG RUBY_VERSION=3.4.7
ARG BASE_IMAGE=registry.odds.team/odds/todo/juacompe-todo-rails/base:latest
FROM ${BASE_IMAGE} AS base

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install application gems
COPY Gemfile Gemfile.lock vendor ./

RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    # -j 1 disable parallel compilation to avoid a QEMU bug: https://github.com/rails/bootsnap/issues/495
    bundle exec bootsnap precompile -j 1 --gemfile

# This image can be pushed to registry for reuse
# End of buildtool stage